error: suggest parentheses around comparison in operand of '&' [-Werror=parentheses]
nandakore

naze umaku ikanai

unused vars

is address be zero?

node is unused